-- V1: core persistence schema (PERS-01/02).
-- Portable ANSI DDL — runs unchanged on H2 (dev) and PostgreSQL (prod).
-- Payload/metadata use CLOB (TEXT) for portability: H2 and PG both accept it,
-- and the Exposed store (de)serializes JSON via the PolymorphicSerializer.
-- JSONB/GIN indexing is NOT required by PERS-01..03; a PG-only ALTER+GIN
-- migration can be added later if analytics querying is needed.

create table sessions (
    id         varchar(128) not null primary key,
    name       varchar(256),
    created_at timestamp    not null,
    scenario   varchar(256),
    tenant_id  varchar(128),          -- declared now (Plan 03 populates) to avoid a second migration
    metadata   clob
);

create table events (
    id         bigint       generated by default as identity primary key,
    session_id varchar(128) not null,
    seq        bigint       not null,
    kind       varchar(128) not null,
    ts_nanos   bigint       not null,
    payload    clob         not null,
    constraint fk_events_session foreign key (session_id) references sessions (id) on delete cascade
);

create index idx_events_session_seq on events (session_id, seq);

create table shares (
    token            varchar(64)  not null primary key,
    session_id       varchar(128) not null,
    created_by       varchar(128) not null,
    created_at       timestamp    not null,
    expires_at       timestamp,
    permission       varchar(16)  not null default 'READ_ONLY',
    access_count     integer      not null default 0,
    last_accessed_at timestamp,
    constraint fk_shares_session foreign key (session_id) references sessions (id) on delete cascade
);

create index idx_shares_session on shares (session_id);
create index idx_shares_expires_at on shares (expires_at);
